/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vue;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author mon pc
 */
public class CreationUtilisateur extends javax.swing.JFrame {

    /**
     * Creates new form CreationUtilisateur
     */
    int selectedrow;
    private String prenom;
    private String type;
    DefaultTableModel d = new DefaultTableModel();
    public CreationUtilisateur() {
        initComponents();
    }
    public CreationUtilisateur(String prenom, String type){
        initComponents();
        d = (DefaultTableModel) tableAffichage.getModel();
        affichageTableau();
        this.prenom = prenom;
        this.type = type; 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fermer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblPrenomUser = new javax.swing.JLabel();
        lblEmailUser = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblMdpUser = new javax.swing.JLabel();
        lblPseudoUser = new javax.swing.JLabel();
        idUser = new javax.swing.JLabel();
        txtPrenomUser = new javax.swing.JTextField();
        txtNomUser = new javax.swing.JTextField();
        txtEmailUser = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtPseudoUser = new javax.swing.JTextField();
        txtMdpUser = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        btnAjouterUser = new javax.swing.JButton();
        btnModifierUser = new javax.swing.JButton();
        btnSupprimerUser = new javax.swing.JButton();
        btnEffacerUser = new javax.swing.JButton();
        lblPseudoUser1 = new javax.swing.JLabel();
        txtAdresse = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAffichage = new javax.swing.JTable();
        lblNomUser1 = new javax.swing.JLabel();
        ComboUserType = new javax.swing.JComboBox<>();
        lblNomUser2 = new javax.swing.JLabel();
        lblNomUser3 = new javax.swing.JLabel();
        lblNomUser4 = new javax.swing.JLabel();
        nbUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREATION DES UTILUSATEURS");

        fermer.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        fermer.setForeground(new java.awt.Color(204, 0, 255));
        fermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/ios7-arrow-thin-left.png"))); // NOI18N
        fermer.setText("Fermer");
        fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1219, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fermer, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fermer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblPrenomUser.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        lblPrenomUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrenomUser.setText("PRENOM");

        lblEmailUser.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        lblEmailUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmailUser.setText("EMAIL");

        jLabel4.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TEL");

        lblMdpUser.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        lblMdpUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMdpUser.setText("MOT DE PASS");

        lblPseudoUser.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        lblPseudoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPseudoUser.setText("Adresse");

        idUser.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        idUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idUser.setText("identifiant");

        txtPrenomUser.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtNomUser.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtEmailUser.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtTel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtPseudoUser.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtPseudoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPseudoUserActionPerformed(evt);
            }
        });

        txtMdpUser.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/ajout.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");

        btnAjouterUser.setBackground(new java.awt.Color(0, 51, 0));
        btnAjouterUser.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        btnAjouterUser.setForeground(new java.awt.Color(0, 204, 102));
        btnAjouterUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/person-add.png"))); // NOI18N
        btnAjouterUser.setText("AJOUTER");
        btnAjouterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterUserActionPerformed(evt);
            }
        });

        btnModifierUser.setBackground(new java.awt.Color(255, 51, 0));
        btnModifierUser.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        btnModifierUser.setForeground(new java.awt.Color(242, 242, 242));
        btnModifierUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/edit.png"))); // NOI18N
        btnModifierUser.setText("MODIFIER");
        btnModifierUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierUserActionPerformed(evt);
            }
        });

        btnSupprimerUser.setBackground(new java.awt.Color(153, 0, 51));
        btnSupprimerUser.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        btnSupprimerUser.setForeground(new java.awt.Color(242, 242, 242));
        btnSupprimerUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/ios7-trash-outline.png"))); // NOI18N
        btnSupprimerUser.setText("SUPPRIMER");
        btnSupprimerUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerUserActionPerformed(evt);
            }
        });

        btnEffacerUser.setBackground(new java.awt.Color(51, 51, 255));
        btnEffacerUser.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        btnEffacerUser.setForeground(new java.awt.Color(242, 242, 242));
        btnEffacerUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/trash-b.png"))); // NOI18N
        btnEffacerUser.setText("EFFACER");
        btnEffacerUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacerUserActionPerformed(evt);
            }
        });

        lblPseudoUser1.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        lblPseudoUser1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPseudoUser1.setText("PSEUDO");

        txtAdresse.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtAdresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdresseActionPerformed(evt);
            }
        });

        tableAffichage.setBackground(new java.awt.Color(51, 51, 51));
        tableAffichage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableAffichage.setForeground(new java.awt.Color(255, 255, 255));
        tableAffichage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableAffichage.setGridColor(new java.awt.Color(0, 0, 0));
        tableAffichage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAffichageMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableAffichageMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tableAffichage);

        lblNomUser1.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        lblNomUser1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomUser1.setText("NOM");

        ComboUserType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ComboUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Admin", "User" }));
        ComboUserType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ComboUserTypeMousePressed(evt);
            }
        });
        ComboUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboUserTypeActionPerformed(evt);
            }
        });

        lblNomUser2.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        lblNomUser2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomUser2.setText("Type User");

        lblNomUser3.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        lblNomUser3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomUser3.setText("ID");

        lblNomUser4.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        lblNomUser4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomUser4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/person.png"))); // NOI18N
        lblNomUser4.setText("nombre d'utilisateur :");

        nbUser.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        nbUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nbUser.setText("ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrenomUser, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMdpUser, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPseudoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPseudoUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblNomUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSupprimerUser, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAjouterUser)))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPseudoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPrenomUser)
                                    .addComponent(txtEmailUser)
                                    .addComponent(txtTel)
                                    .addComponent(txtMdpUser, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txtNomUser, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(ComboUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(209, 209, 209)))
                    .addComponent(idUser, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnModifierUser, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEffacerUser, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNomUser4, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(lblNomUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1102, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(lblNomUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1177, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtNomUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrenomUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrenomUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtEmailUser)
                                .addGap(3, 3, 3)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMdpUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtMdpUser)
                                .addGap(3, 3, 3))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtPseudoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblPseudoUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPseudoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(ComboUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifierUser))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEffacerUser)
                    .addComponent(btnSupprimerUser))
                .addGap(42, 42, 42))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomUser4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblNomUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(527, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(306, Short.MAX_VALUE)
                    .addComponent(lblNomUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(237, 237, 237)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPseudoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPseudoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPseudoUserActionPerformed

    private void txtAdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdresseActionPerformed

    private void btnAjouterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterUserActionPerformed
        //Codage du Boutton Ajouter Un utilisateur
        try {
            Connect con = new Connect();
            String type = (String) ComboUserType.getSelectedItem();
            
         String  select = "select * from utilisateur where email = ? and pseudo = ? and tel = ? and mdp = ?";
         PreparedStatement st = con.con.prepareStatement(select);
         st.setString(1, txtEmailUser.getText());
         st.setString(2, txtPseudoUser.getText());
         st.setString(3, txtTel.getText());
         st.setString(4, txtMdpUser.getText());
         ResultSet r = st.executeQuery();
         if(r.next()){
             JOptionPane.showMessageDialog(this, "Désolé il y'a déja un Utilisateur\n"+
                     "qui à "+
                     "Email : "+r.getString("email")+"\n"
                     +"Pseudo : "+r.getString("pseudo")+"\n"
                     +"Tel : "+r.getString("email")+"\n"
                     + "Veuillez saisir autre que ceux_là+");
         }
            // On vérifie s'il y'a au moins un champ nont requit
         else if(txtNomUser.getText().trim().isEmpty() || txtPrenomUser.getText().trim().isEmpty()
                    || txtTel.getText().trim().isEmpty() || txtMdpUser.getText().trim().isEmpty()
                    || txtAdresse.getText().trim().isEmpty() || txtPseudoUser.getText().trim().isEmpty()
                    || txtEmailUser.getText().trim().isEmpty() || type.trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Echec d'insertion\n Il ya au moins un champ n'on remplit\n"
                +"SVP veuillez le remplir !!");
            }
            else{
                //établissement de la connection à la base
                
                //Préparation de la reqûte sql
                String sql = "insert into utilisateur(nom, prenom, tel, mdp, email, adresse, pseudo, type_user)"
                        + "values(?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement  pst = (PreparedStatement) con.con.prepareStatement(sql);
                //on set les parametres
                pst.setString(1, txtNomUser.getText());
                pst.setString(2, txtPrenomUser.getText());
                pst.setString(3, txtTel.getText());
                pst.setString(4, txtMdpUser.getText());
                pst.setString(5, txtEmailUser.getText());
                pst.setString(6, txtAdresse.getText());
                pst.setString(7, txtPseudoUser.getText());
                pst.setString(8, (String) ComboUserType.getSelectedItem());
                //Execution de la requete
                int nbupdate = pst.executeUpdate();
                if(nbupdate > 0){
                    JOptionPane.showMessageDialog(this, "Insertion de "+txtNomUser.getText()+" à reussi !!");
                    affichageTableau();
                }else{
                    JOptionPane.showMessageDialog(this, "Echec d'insertion");
                }
                con.con.close();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur ici !!"+e.getMessage());
        }
    }//GEN-LAST:event_btnAjouterUserActionPerformed

    private void fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerActionPerformed
        //codage du boutton de fermeture
        super.dispose();
        Home home = new Home(this.prenom, this.type);
        home.setLocationRelativeTo(null);
         home.setVisible(true);
    }//GEN-LAST:event_fermerActionPerformed

    private void ComboUserTypeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboUserTypeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboUserTypeMousePressed

    private void ComboUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboUserTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboUserTypeActionPerformed

    private void btnEffacerUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacerUserActionPerformed
        //Codage du bouton effacer qui va vider les champs
        txtMdpUser.setText("");
        txtEmailUser.setText("");
        txtPrenomUser.setText("");
        txtTel.setText("");
        txtAdresse.setText("");
        txtPseudoUser.setText("");
        txtNomUser.setText("");
    }//GEN-LAST:event_btnEffacerUserActionPerformed

    private void tableAffichageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAffichageMouseClicked
        // L'événement de clic sur une ligne

    }//GEN-LAST:event_tableAffichageMouseClicked

    private void btnSupprimerUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerUserActionPerformed
        //codage du boutton supprimer
        try {
            //appel à la connection
            Connect con = new Connect();
            //Une requête sql préparer 
            String sql = "delete  from utilisateur where email = ?";
            PreparedStatement pt = con.con.prepareStatement(sql);
            pt.setString(1, txtEmailUser.getText());
            //execution de la réqûete 
           int n = pt.executeUpdate();
           //si on arrive à return une ligne alors on fait la suppréssion; sinon on affiche un message 
           if(n != 0){
                    JOptionPane.showMessageDialog(this, "Suppression de "+txtNomUser.getText()
                 +" reussi !!");
                 affichageTableau();
                 con.con.close();
           }else{
               JOptionPane.showMessageDialog(this, "Aucune donnée selectionée");
           }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Echec de suppression !!");
        }
    }//GEN-LAST:event_btnSupprimerUserActionPerformed

    private void tableAffichageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAffichageMousePressed
       int i = tableAffichage.getSelectedRow();
       DefaultTableModel model = (DefaultTableModel) tableAffichage.getModel();
       txtNomUser.setText(model.getValueAt(i, 0).toString());
       txtPrenomUser.setText(model.getValueAt(i, 1).toString());
       txtEmailUser.setText(model.getValueAt(i, 2).toString());
       txtTel.setText(model.getValueAt(i, 3).toString());
        txtMdpUser.setText(model.getValueAt(i, 4).toString());
        txtPseudoUser.setText(model.getValueAt(i, 5).toString());
        txtAdresse.setText(model.getValueAt(i, 6).toString());
        idUser.setText( model.getValueAt(i, 8).toString());
    }//GEN-LAST:event_tableAffichageMousePressed

    private void btnModifierUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierUserActionPerformed
        // Codage du boutton modifier
        try {
            //établissement de la connection
            String type = (String) ComboUserType.getSelectedItem();
            Connect con = new Connect();
            //écriture de la requete qui fera la modification
            String sql = "UPDATE utilisateur SET nom =? , prenom =? , tel = ?  , mdp =? , adresse = ? , email = ?, pseudo = ? where id = "+idUser.getText();
            PreparedStatement pst = con.con.prepareStatement(sql);
            pst.setString(1, txtNomUser.getText());
                pst.setString(2, txtPrenomUser.getText());
                pst.setString(3, txtTel.getText());
                pst.setString(4, txtMdpUser.getText());
                pst.setString(5, txtEmailUser.getText());
                pst.setString(6, txtAdresse.getText());
                pst.setString(7, txtPseudoUser.getText());
                
                int valide = pst.executeUpdate();
                if(valide != 0){
                    JOptionPane.showMessageDialog(this, valide+" modification éffectué");
                    affichageTableau();
                    con.con.close();
                }else{
                    JOptionPane.showMessageDialog(this, valide+" modification éffectué");
                }
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " Echec de modification"+e.getMessage());
        }
    }//GEN-LAST:event_btnModifierUserActionPerformed

    
    /**
     * @param args the command line arguments
     */
//creation de la fonction affichage information
    public void affichageTableau(){
        try {
            Connect con = new Connect();
            String [] entete = {"Nom", "Prénom",
                "Email", "Tel", "Mdp", "Pseudo",
                 "Adresse","Type User", "ID"};
            String [] Afficher = new String[15];
            DefaultTableModel model = new DefaultTableModel(null, entete);
            Statement st = con.con.createStatement();
            ResultSet rs = st.executeQuery("select * from utilisateur");
            
            while(rs.next()){
                 Afficher[0] = rs.getString("nom");
                 Afficher[1] = rs.getString("prenom");
                 Afficher[2] = rs.getString("email");
                 Afficher[3] = rs.getString("tel");
                 Afficher[4] = rs.getString("mdp");
                 Afficher[5] = rs.getString("pseudo");
                 Afficher[6] = rs.getString("adresse");
                 Afficher[7] = rs.getString("type_user");
                 Afficher[8] = rs.getString("id");
                 model.addRow(Afficher);
                 
            }
            tableAffichage.setModel(model);
           int i = tableAffichage.getRowCount();
            nbUser.setText(String.valueOf(i));
            
           con.con.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erreur "+ex.getMessage());
        }
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreationUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreationUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreationUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreationUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreationUtilisateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboUserType;
    private javax.swing.JButton btnAjouterUser;
    private javax.swing.JButton btnEffacerUser;
    private javax.swing.JButton btnModifierUser;
    private javax.swing.JButton btnSupprimerUser;
    private javax.swing.JButton fermer;
    private javax.swing.JLabel idUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEmailUser;
    private javax.swing.JLabel lblMdpUser;
    private javax.swing.JLabel lblNomUser1;
    private javax.swing.JLabel lblNomUser2;
    private javax.swing.JLabel lblNomUser3;
    private javax.swing.JLabel lblNomUser4;
    private javax.swing.JLabel lblPrenomUser;
    private javax.swing.JLabel lblPseudoUser;
    private javax.swing.JLabel lblPseudoUser1;
    private javax.swing.JLabel nbUser;
    private javax.swing.JTable tableAffichage;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtEmailUser;
    private javax.swing.JPasswordField txtMdpUser;
    private javax.swing.JTextField txtNomUser;
    private javax.swing.JTextField txtPrenomUser;
    private javax.swing.JTextField txtPseudoUser;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
