/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vue;

/**
 *
 * @author mon pc
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    private String type;
    private String prenom;
    public Home(String prenom,String type){
        initComponents();
        this.type = type;
        this.prenom = prenom;
        txtbienvenu.setText("Bienvenu M./Me "+this.prenom);
        if(this.type.equals("User")){
            btnAjouterUsersMenu.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnLibMenu = new javax.swing.JButton();
        btnHistMenu = new javax.swing.JButton();
        btnProfilMenu = new javax.swing.JButton();
        btnAjouterUsersMenu = new javax.swing.JButton();
        btnEnrMenu = new javax.swing.JButton();
        btnDecMenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEnrMenu1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtbienvenu = new javax.swing.JLabel();

        jButton6.setBackground(new java.awt.Color(102, 102, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jButton6.setText("Enregistrement");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnLibMenu.setBackground(new java.awt.Color(204, 0, 204));
        btnLibMenu.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnLibMenu.setForeground(new java.awt.Color(242, 242, 242));
        btnLibMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/arrow-right-c.png"))); // NOI18N
        btnLibMenu.setText("Libération");
        btnLibMenu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/ios7-arrow-thin-right.png"))); // NOI18N
        btnLibMenu.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnLibMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibMenuActionPerformed(evt);
            }
        });

        btnHistMenu.setBackground(new java.awt.Color(204, 0, 204));
        btnHistMenu.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnHistMenu.setForeground(new java.awt.Color(242, 242, 242));
        btnHistMenu.setText("Voir Historique");

        btnProfilMenu.setBackground(new java.awt.Color(204, 0, 204));
        btnProfilMenu.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnProfilMenu.setForeground(new java.awt.Color(242, 242, 242));
        btnProfilMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/person.png"))); // NOI18N
        btnProfilMenu.setText("Mon Profil");
        btnProfilMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilMenuActionPerformed(evt);
            }
        });

        btnAjouterUsersMenu.setBackground(new java.awt.Color(204, 0, 204));
        btnAjouterUsersMenu.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnAjouterUsersMenu.setForeground(new java.awt.Color(242, 242, 242));
        btnAjouterUsersMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/ios7-contact.png"))); // NOI18N
        btnAjouterUsersMenu.setText("Ajouter Users");
        btnAjouterUsersMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterUsersMenuActionPerformed(evt);
            }
        });

        btnEnrMenu.setBackground(new java.awt.Color(204, 0, 204));
        btnEnrMenu.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnEnrMenu.setForeground(new java.awt.Color(242, 242, 242));
        btnEnrMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/arrow-right-c.png"))); // NOI18N
        btnEnrMenu.setText("Enregistrement");
        btnEnrMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrMenuActionPerformed(evt);
            }
        });

        btnDecMenu.setBackground(new java.awt.Color(204, 0, 204));
        btnDecMenu.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnDecMenu.setForeground(new java.awt.Color(242, 242, 242));
        btnDecMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/ios7-arrow-thin-left.png"))); // NOI18N
        btnDecMenu.setText("Déconnexion");
        btnDecMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLibMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHistMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(btnProfilMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAjouterUsersMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnrMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDecMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnEnrMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLibMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHistMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnProfilMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAjouterUsersMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDecMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 0, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(153, 0, 153));

        jLabel1.setBackground(new java.awt.Color(204, 102, 255));
        jLabel1.setFont(new java.awt.Font("Eras Light ITC", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU GENERALE");

        btnEnrMenu1.setBackground(new java.awt.Color(204, 0, 204));
        btnEnrMenu1.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnEnrMenu1.setForeground(new java.awt.Color(242, 242, 242));
        btnEnrMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/android-close.png"))); // NOI18N
        btnEnrMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrMenu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnEnrMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnrMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(javax.swing.UIManager.getDefaults().getColor("Objects.Red"));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MENU");

        txtbienvenu.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        txtbienvenu.setForeground(new java.awt.Color(255, 255, 255));
        txtbienvenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtbienvenu.setText("Bienvenu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(txtbienvenu, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtbienvenu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnrMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrMenuActionPerformed
        // Création d'un objet de type Vue
        
        super.dispose();
        Vue enregistrement = new Vue(this.prenom, this.type);
        enregistrement.setLocationRelativeTo(null);
        enregistrement.setVisible(true);
    }//GEN-LAST:event_btnEnrMenuActionPerformed

    private void btnEnrMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrMenu1ActionPerformed
        // codage du boutton fermer qui rédirige à la vue login
        LoginUsers login = new LoginUsers();
        setVisible(false);
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        
    }//GEN-LAST:event_btnEnrMenu1ActionPerformed

    private void btnLibMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibMenuActionPerformed
        //Codage du bouton menu Liberation
        super.dispose();
        Liberation liberer = new Liberation(this.prenom, this.type);
        liberer.setLocationRelativeTo(null);
        liberer.setVisible(true);
    }//GEN-LAST:event_btnLibMenuActionPerformed

    private void btnProfilMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilMenuActionPerformed
        //Codage du bouton menu profil
        Profil profil = new Profil();
        profil.setLocationRelativeTo(null);
        this.setVisible(false);
        profil.setVisible(true);
    }//GEN-LAST:event_btnProfilMenuActionPerformed

    private void btnAjouterUsersMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterUsersMenuActionPerformed
        //Codage du bouton menu Ajouter un user
        CreationUtilisateur user = new CreationUtilisateur(this.prenom, this.type);
        user.setLocationRelativeTo(null);
        this.setVisible(false);
        user.setVisible(true);
    }//GEN-LAST:event_btnAjouterUsersMenuActionPerformed

    private void btnDecMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecMenuActionPerformed
         // codage du boutton Déconnection qui rédirige à la vue login
        LoginUsers login = new LoginUsers();
        setVisible(false);
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }//GEN-LAST:event_btnDecMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                Home home = new Home();
                home.setLocationRelativeTo(null);
                home.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterUsersMenu;
    private javax.swing.JButton btnDecMenu;
    private javax.swing.JButton btnEnrMenu;
    private javax.swing.JButton btnEnrMenu1;
    private javax.swing.JButton btnHistMenu;
    private javax.swing.JButton btnLibMenu;
    private javax.swing.JButton btnProfilMenu;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtbienvenu;
    // End of variables declaration//GEN-END:variables
}
