/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vue;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.util.Date;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author mon pc
 */
public class Vue extends javax.swing.JFrame {

    /**
     * Creates new form Vue
     */
    private int id ;
    public Vue(String prenom, String type) {
        initComponents();
        affichageInfoClient();
        dateDujour();
        this.prenom = prenom;
        this.type = type;
        txtbienvenu.setText(prenom);
       
    }
    private String prenom;
    private String type;
    public Vue(){
        initComponents();
        affichageInfoClient();
        dateDujour();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblDateVue = new javax.swing.JLabel();
        lblPrenomVue = new javax.swing.JLabel();
        txtPrenomVue = new javax.swing.JTextField();
        txtNomVue = new javax.swing.JTextField();
        lblNomVue = new javax.swing.JLabel();
        lblTelVue = new javax.swing.JLabel();
        txtTelVue = new javax.swing.JTextField();
        lblUmatVue = new javax.swing.JLabel();
        txtUmatVue = new javax.swing.JTextField();
        comboTypeEnginVue = new javax.swing.JComboBox<>();
        lblTypeVue = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblPlaceOccpVue = new javax.swing.JLabel();
        dateEnregistrement = new javax.swing.JLabel();
        btnAjouterUser = new javax.swing.JButton();
        btnModifierUser = new javax.swing.JButton();
        btnSupprimerUser = new javax.swing.JButton();
        btnEffacerUser = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lblPlaceRestVue1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnAjouterVue = new javax.swing.JButton();
        txtbienvenu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableafficheClient = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 102));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblDateVue.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        lblDateVue.setForeground(new java.awt.Color(204, 204, 255));
        lblDateVue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDateVue.setText("DATE ENTREE");

        lblPrenomVue.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        lblPrenomVue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrenomVue.setText("PRENOM");

        txtPrenomVue.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtPrenomVue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNomVue.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtNomVue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblNomVue.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        lblNomVue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomVue.setText("NOM");

        lblTelVue.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        lblTelVue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTelVue.setText("TELEPHONE");

        txtTelVue.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtTelVue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblUmatVue.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        lblUmatVue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUmatVue.setText("UMATRICULATION");

        txtUmatVue.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtUmatVue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        comboTypeEnginVue.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        comboTypeEnginVue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "MOTO", "AUTO" }));
        comboTypeEnginVue.setToolTipText("");
        comboTypeEnginVue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboTypeEnginVueMouseClicked(evt);
            }
        });
        comboTypeEnginVue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTypeEnginVueActionPerformed(evt);
            }
        });

        lblTypeVue.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        lblTypeVue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTypeVue.setText("TYPE D'ENGIN");

        jLabel11.setBackground(new java.awt.Color(204, 51, 0));
        jLabel11.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("NOMBRE PLACE OCCUPEES");

        lblPlaceOccpVue.setFont(new java.awt.Font("Eras Light ITC", 1, 24)); // NOI18N
        lblPlaceOccpVue.setForeground(java.awt.Color.red);
        lblPlaceOccpVue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaceOccpVue.setText("0");

        dateEnregistrement.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        dateEnregistrement.setForeground(new java.awt.Color(51, 255, 0));
        dateEnregistrement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateEnregistrement.setText("Date jour");

        btnAjouterUser.setBackground(new java.awt.Color(0, 51, 0));
        btnAjouterUser.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        btnAjouterUser.setForeground(new java.awt.Color(0, 204, 102));
        btnAjouterUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/person-add.png"))); // NOI18N
        btnAjouterUser.setText("AJOUTER");
        btnAjouterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterUserActionPerformed(evt);
            }
        });

        btnModifierUser.setBackground(new java.awt.Color(255, 51, 0));
        btnModifierUser.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        btnModifierUser.setForeground(new java.awt.Color(242, 242, 242));
        btnModifierUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/edit.png"))); // NOI18N
        btnModifierUser.setText("MODIFIER");
        btnModifierUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierUserActionPerformed(evt);
            }
        });

        btnSupprimerUser.setBackground(new java.awt.Color(153, 0, 51));
        btnSupprimerUser.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        btnSupprimerUser.setForeground(new java.awt.Color(242, 242, 242));
        btnSupprimerUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/ios7-trash-outline.png"))); // NOI18N
        btnSupprimerUser.setText("SUPPRIMER");
        btnSupprimerUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerUserActionPerformed(evt);
            }
        });

        btnEffacerUser.setBackground(new java.awt.Color(51, 51, 255));
        btnEffacerUser.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        btnEffacerUser.setForeground(new java.awt.Color(242, 242, 242));
        btnEffacerUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/trash-b.png"))); // NOI18N
        btnEffacerUser.setText("EFFACER");
        btnEffacerUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacerUserActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(204, 51, 0));
        jLabel13.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("NOMBRE PLACE RESTANT");

        lblPlaceRestVue1.setFont(new java.awt.Font("Eras Light ITC", 1, 24)); // NOI18N
        lblPlaceRestVue1.setForeground(new java.awt.Color(102, 255, 102));
        lblPlaceRestVue1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaceRestVue1.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAjouterUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnModifierUser, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSupprimerUser, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(btnEffacerUser, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblPlaceOccpVue, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblPlaceRestVue1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomVue, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUmatVue, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrenomVue, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrenomVue, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelVue, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboTypeEnginVue, 0, 148, Short.MAX_VALUE)
                                    .addComponent(txtUmatVue))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(dateEnregistrement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTelVue, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblDateVue, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(lblNomVue, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(351, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(lblTypeVue, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(310, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblPrenomVue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrenomVue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomVue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelVue, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUmatVue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelVue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUmatVue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblDateVue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboTypeEnginVue, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateEnregistrement, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlaceRestVue1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlaceOccpVue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifierUser))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupprimerUser)
                    .addComponent(btnEffacerUser))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblNomVue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(507, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(185, 185, 185)
                    .addComponent(lblTypeVue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(332, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jLabel15.setBackground(new java.awt.Color(153, 51, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(242, 242, 242));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("GESTION CLIENTS");
        jLabel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel16.setBackground(new java.awt.Color(153, 51, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(242, 242, 242));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("LISTE DES ENREGISTRES");
        jLabel16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAjouterVue.setBackground(new java.awt.Color(204, 0, 204));
        btnAjouterVue.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnAjouterVue.setForeground(new java.awt.Color(242, 242, 242));
        btnAjouterVue.setText("Rétour");
        btnAjouterVue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterVueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAjouterVue, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAjouterVue, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtbienvenu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtbienvenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtbienvenu.setText("BIENVEUNU MR/MD ");

        tableafficheClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableafficheClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableafficheClientMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tableafficheClient);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtbienvenu, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(txtbienvenu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterVueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterVueActionPerformed
        // TODO add your handling code here:
        super.dispose();
       Home home = new Home(this.prenom, this.type);
       home.setLocationRelativeTo(null);
       home.setVisible(true);
        
    }//GEN-LAST:event_btnAjouterVueActionPerformed

    private void btnAjouterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterUserActionPerformed
        //Codage du boutton Ajouter
         Connect con = new Connect();
         
         //On crée la date du moment pour inserer automatiquement la date du jour
        Date dateactuelle = new Date();
        DateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateformat.format(dateactuelle);
        String dc = date;
        
        String prix;
        
        /*
        Dans cet bloc try_catch on fait les vérifications et l'insertion
        On vérifie si tous les champs sont vide
            Si oui on affiche un message d'eure
        Sinon 
            On fait une requet select pour comparer La plaque et type d'engin s'il ne sont pas déjà dans la bd
        sinon
            On fait l'insertion avec une requet preparer  du client
            La date est ajouté automatique avec la variable dc
            Le prix est ajouté automatique en fonction du type_engin
            si type = auto ->5000
            sinon ->3000
        
        */
        try {
                //Vérifiecation du contenu des champs
                
                if(txtNomVue.getText().trim().isEmpty()|| txtPrenomVue.getText().trim().isEmpty() ||
                    txtTelVue.getText().trim().isEmpty() || txtUmatVue.getText().trim().isEmpty()
                        || comboTypeEnginVue.getSelectedItem().toString().trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "SVP !! Veuillez remplir les champs"
                            + "\n il y'a au moins un champs vide", "Alerte", JOptionPane.WARNING_MESSAGE);
                }
                else{
                    //Vérification dans la base de donnée siblan la plaque et type
                        String sqlSelection = "select * from enregistrement where immat_Engin = ? and type_Engin = ?";
                        PreparedStatement ps = con.con.prepareStatement(sqlSelection);
                        ps.setString(1, txtUmatVue.getText());
                        ps.setString(2, comboTypeEnginVue.getSelectedItem().toString());
                        ResultSet rs = ps.executeQuery();
                        if(rs.next()){
                            this.id = rs.getInt("id");
                            JOptionPane.showMessageDialog(this, "Erreur d'insertion\n"
                                    + "il y'a déjà cette Ummatriculation "+rs.getString("immat_Engin")+" "
                                            + "Pour un client", "Alerte", JOptionPane.WARNING_MESSAGE);
                        }
                        //Si aucune ligne ne correspont a la requete on fait l'insertion
                        else{
                            //Ici on fixe le prix enfonction du typee d'engin M->3000, A->5000
                            if(comboTypeEnginVue.getSelectedItem().toString().equals("MOTO")){
                                prix = "3000";
                            }else{prix = "5000";}
                            //la requete sql 
                            String sql = "insert into enregistrement(nom_client, prenom_client, tel, immat_Engin, type_Engin, date_entree,prix)"
                            + "values(?,?,?,?,?,'"+dc+"',?)";
                                //préparation de la requete et execution de la requet
                           PreparedStatement  pst = (PreparedStatement) con.con.prepareStatement(sql);
                           pst.setString(1, txtNomVue.getText());
                           pst.setString(2, txtPrenomVue.getText());
                           pst.setString(3, txtTelVue.getText());
                           pst.setString(4, txtUmatVue.getText());
                           pst.setString(5, comboTypeEnginVue.getSelectedItem().toString());
                           pst.setString(6,prix);
                           pst.executeUpdate();
                           JOptionPane.showMessageDialog(this, "Insertion effectuée");
                        }
                         affichageInfoClient();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur d'insertion "+e.getMessage(),"Alerte", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAjouterUserActionPerformed

    private void btnModifierUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierUserActionPerformed
        //Codage du boutton Modifier
        try {
            Connect con = new Connect();
            String sql = "update enregistrement set nom_client =?, prenom_client=?, tel=?, immat_Engin=?, type_Engin=?"
                    + "where id = ?";
            PreparedStatement st = con.con.prepareStatement(sql);
            st.setString(1, txtNomVue.getText());
            st.setString(2, txtPrenomVue.getText());
            st.setString(3, txtTelVue.getText());
            st.setString(4, txtUmatVue.getText());
            st.setString(5, comboTypeEnginVue.getSelectedItem().toString());
            st.setString(6, String.valueOf(id));
            
            int nupdate = st.executeUpdate();
            if(nupdate != 0){
                JOptionPane.showMessageDialog(this, "reussi");
                affichageInfoClient();
            }else{
                JOptionPane.showMessageDialog(this, "echec");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "erreur "+e.getMessage());
        }
    }//GEN-LAST:event_btnModifierUserActionPerformed

    /*
        Ici on n'a codé le bouton de supression
        Si les donnée sont selectionné on démande à l'utilisateur s'il est sur de proceder
            si oui -> on fait la suppresion commit()
            si non -> on annule la supression rollbak ()
        sinon on lui dit qu'il n'a selectionné aucune donnée
    */
    private void btnSupprimerUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerUserActionPerformed
        //codage du boutton supprimern
        try {
            Connect con = new Connect();
            con.con.setAutoCommit(false);
            String sql = "delete from enregistrement where immat_Engin =? ";
            PreparedStatement pst = con.con.prepareStatement(sql);
            pst.setString(1, txtUmatVue.getText());
            int n =  pst.executeUpdate();
            if(n != 0){
               int option = JOptionPane.showConfirmDialog(this, "Êtes-vous sûr ?");
               if(option == JOptionPane.YES_OPTION){
                   con.con.commit();
                   JOptionPane.showMessageDialog(this, "Supression Reussi");
                   affichageInfoClient();
               }else{
                   con.con.rollback();
                   JOptionPane.showMessageDialog(this, "Supression Annuler");
               }
            }else{
                JOptionPane.showMessageDialog(this, "aucune donnée  selectionnée");
            }
           con.con.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "de la merde "+e.getMessage());
        }
    }//GEN-LAST:event_btnSupprimerUserActionPerformed

    private void btnEffacerUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacerUserActionPerformed
        //Effacer le formulaire
        txtNomVue.setText("");
        txtPrenomVue.setText("");
        txtTelVue.setText("");
        txtUmatVue.setText("");
    }//GEN-LAST:event_btnEffacerUserActionPerformed

    private void comboTypeEnginVueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTypeEnginVueActionPerformed
  
    }//GEN-LAST:event_comboTypeEnginVueActionPerformed

    private void comboTypeEnginVueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTypeEnginVueMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTypeEnginVueMouseClicked

    private void tableafficheClientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableafficheClientMousePressed
        // Quand on presse sur un élément du tableau
        int i = tableafficheClient.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tableafficheClient.getModel();
        txtNomVue.setText(model.getValueAt(i, 0).toString());
        txtPrenomVue.setText(model.getValueAt(i, 1).toString());
        txtUmatVue.setText(model.getValueAt(i, 2).toString());
        txtTelVue.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_tableafficheClientMousePressed

    public void dateDujour(){
        Date actuel = new Date();
        DateFormat dateformat = new SimpleDateFormat("yyy-MM-dd");
        String date = dateformat.format(actuel);
        dateEnregistrement.setText(date);
    }
    /**
     * @param args the command line arguments
     */
    //codage de la fonction affichageInfoClient
    public void affichageInfoClient(){
        int taille = 30;
        String [] header = {
            "Nom", "Prénom", "Immatriculation", "Type Engin","Tel", "Prix","Date entrée"
            };
        String [] Affichage = new String[30];
        DefaultTableModel model = new DefaultTableModel(null, header);
        try {
            Connect con = new Connect();
            //la requete sql
            String sql = "select * from enregistrement order by  date_entree desc";
            //preparation de la requete
            PreparedStatement pst = con.con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                Affichage[0] = rs.getString("nom_client");
                Affichage[1] = rs.getString("prenom_client");
                Affichage[2] = rs.getString("immat_Engin");
                Affichage[3] = rs.getString("type_Engin");
                Affichage[4] = rs.getString("tel");
                Affichage[5] = rs.getString("prix");
                Affichage[6] = rs.getString("date_entree");
                model.addRow(Affichage);
            }
            tableafficheClient.setModel(model);
            //on récupère le nombre de colonne du tableau
            int i = tableafficheClient.getRowCount();
            //on affiche le nbre de place occupé
            lblPlaceOccpVue.setText(String.valueOf(i));
            //on affiche le nombre restant
            lblPlaceRestVue1.setText(String.valueOf(taille - i));
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur ici : "+e.getMessage());
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Vue f = new Vue();
                f.setLocationRelativeTo(null);
               f.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterUser;
    private javax.swing.JButton btnAjouterVue;
    private javax.swing.JButton btnEffacerUser;
    private javax.swing.JButton btnModifierUser;
    private javax.swing.JButton btnSupprimerUser;
    private javax.swing.JComboBox<String> comboTypeEnginVue;
    private javax.swing.JLabel dateEnregistrement;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDateVue;
    private javax.swing.JLabel lblNomVue;
    private javax.swing.JLabel lblPlaceOccpVue;
    private javax.swing.JLabel lblPlaceRestVue1;
    private javax.swing.JLabel lblPrenomVue;
    private javax.swing.JLabel lblTelVue;
    private javax.swing.JLabel lblTypeVue;
    private javax.swing.JLabel lblUmatVue;
    private javax.swing.JTable tableafficheClient;
    private javax.swing.JTextField txtNomVue;
    private javax.swing.JTextField txtPrenomVue;
    private javax.swing.JTextField txtTelVue;
    private javax.swing.JTextField txtUmatVue;
    private javax.swing.JLabel txtbienvenu;
    // End of variables declaration//GEN-END:variables
}
